export const API_CODE = {
	SUCCESS: 'SUCCESS',
	NOT_FOUND: 'NOT_FOUND',
	BAD_REQUEST: 'BAD_REQUEST',
	UNAUTHORIZED: 'UNAUTHORIZED',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	INVALID: 'INVALID',
} as const

export type ApiCode = (typeof API_CODE)[keyof typeof API_CODE]
