export const mockCategories = [
	{
		id: 1,
		name: 'Fast Food',
		description: 'Quick and tasty fast food',
		imageUrl: 'https://example.com/images/fast-food.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 2,
		name: 'Vietnamese Food',
		description: 'Traditional Vietnamese dishes',
		imageUrl: 'https://example.com/images/vietnamese.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 3,
		name: 'Japanese Food',
		description: 'Sushi, ramen, and more',
		imageUrl: 'https://example.com/images/japanese.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 4,
		name: 'Korean Food',
		description: 'Kimchi, BBQ, and street food',
		imageUrl: 'https://example.com/images/korean.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 5,
		name: 'Chinese Food',
		description: 'Dim sum and traditional dishes',
		imageUrl: 'https://example.com/images/chinese.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 6,
		name: 'Italian Food',
		description: 'Pizza and pasta',
		imageUrl: 'https://example.com/images/italian.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 7,
		name: 'Beverages',
		description: 'Drinks and refreshment',
		imageUrl: 'https://example.com/images/beverage.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 8,
		name: 'Desserts',
		description: 'Sweet desserts and cakes',
		imageUrl: 'https://example.com/images/dessert.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 9,
		name: 'Seafood',
		description: 'Fresh seafood dishes',
		imageUrl: 'https://example.com/images/seafood.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 10,
		name: 'Vegetarian',
		description: 'Healthy vegetarian meals',
		imageUrl: 'https://example.com/images/vegetarian.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	// ---- thêm cho đủ 20 ----
	{
		id: 11,
		name: 'BBQ',
		description: 'Grilled meat and BBQ',
		imageUrl: 'https://example.com/images/bbq.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 12,
		name: 'Hotpot',
		description: 'Hotpot and soup dishes',
		imageUrl: 'https://example.com/images/hotpot.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 13,
		name: 'Breakfast',
		description: 'Breakfast meals',
		imageUrl: 'https://example.com/images/breakfast.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 14,
		name: 'Lunch',
		description: 'Lunch menu',
		imageUrl: 'https://example.com/images/lunch.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 15,
		name: 'Dinner',
		description: 'Dinner menu',
		imageUrl: 'https://example.com/images/dinner.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 16,
		name: 'Street Food',
		description: 'Popular street food',
		imageUrl: 'https://example.com/images/street-food.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 17,
		name: 'Healthy Food',
		description: 'Healthy and diet meals',
		imageUrl: 'https://example.com/images/healthy.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 18,
		name: 'Snacks',
		description: 'Light snacks',
		imageUrl: 'https://example.com/images/snack.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 19,
		name: 'Bakery',
		description: 'Bread and bakery items',
		imageUrl: 'https://example.com/images/bakery.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
	{
		id: 20,
		name: 'Coffee',
		description: 'Coffee and tea',
		imageUrl: 'https://example.com/images/coffee.jpg',
		createdAt: new Date(),
		createdBy: 1,
		updatedAt: null,
		updatedBy: null,
		deletedAt: null,
		deletedBy: null,
		isDeleted: false,
	},
]
